from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


FORBIDDEN_ACTIONS = [
    "Do not commit.",
    "Do not push.",
    "Do not open pull requests.",
    "Do not merge.",
    "Do not tag.",
    "Do not deploy.",
    "Do not run reset, clean, rebase or destructive commands.",
    "Leave the working tree modified for human review.",
]


def build_prompt(*, step: str, title: str, objective: str, branch: str | None = None) -> str:
    branch_text = branch or f"step/{step.lower().replace(' ', '-')}"
    lines = [
        f"# DRAFT Codex Prompt - {step}) {title}",
        "",
        "This is a DRAFT generated by ASF Operator. GPT/Alberto must review it before use.",
        "",
        "## Objective",
        "",
        objective,
        "",
        "## Repository",
        "",
        "C:\\Users\\alberto.ferrari\\source\\repos\\AI_Software_Factory",
        "",
        "## Branch",
        "",
        branch_text,
        "",
        "## Allowed Scope",
        "",
        "- Read the repository.",
        "- Modify only files explicitly needed by this step.",
        "- Keep changes small, testable and documented.",
        "",
        "## Forbidden Actions",
        "",
    ]
    lines.extend(f"- {item}" for item in FORBIDDEN_ACTIONS)
    lines.extend(
        [
            "",
            "## Stop Rule",
            "",
            "- Stop if the working tree has unrelated dirty files.",
            "- Stop if the step requires secrets, live calls, publication or scope expansion.",
            "- Stop if mandatory tests fail and the cause is outside scope.",
            "",
            "## Verification Gate",
            "",
            "- python -m pytest",
            "- python scripts/check_workflow_health.py",
            "- pwsh -NoProfile -ExecutionPolicy Bypass -File scripts\\verify.ps1",
            "- git --no-pager diff --check",
            "- git --no-pager status --short",
            "",
            "## Final Report",
            "",
            "Use Italian and include sections A-J from AGENTS.md. Confirm forbidden actions were not performed.",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a controlled DRAFT Codex prompt.")
    parser.add_argument("--step", required=True)
    parser.add_argument("--title", required=True)
    parser.add_argument("--objective", required=True)
    parser.add_argument("--branch")
    parser.add_argument("--output")
    parser.add_argument("--json", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    prompt = build_prompt(step=args.step, title=args.title, objective=args.objective, branch=args.branch)
    if args.output:
        Path(args.output).write_text(prompt + "\n", encoding="utf-8")
    if args.json:
        print(json.dumps({"prompt": prompt, "output": args.output, "draft": True}, indent=2, sort_keys=True))
    else:
        print(prompt)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
